// Unit tests for Ridge Quest's corridor-run detector in frontend/ridge-quest.html:
//   - QGeo.corridorDist / projectOnPath (signed-distance + along-corridor math)
//   - QGeo.evaluateTraversal, via Quest._classifyAndLog: does a recorded track
//     amount to a real END-TO-END pass of a corridor (start/end zones in order,
//     bin coverage, off-route, direction/bearing, speed/time, elevation)?
//   - the classification that follows (ski/lift/hike/bike/xcski/drive)
//   - Quest._tick: the narration band AND the run recorder that drives logging
//
// 2026-09-21 field report that motivated the rewrite: skiing ACROSS corridors
// (a traverse) logged them as skied. The old test fixtures fed physically
// impossible tracks (a 1.1 km jump in 2 s with speed:1), which is exactly why
// nothing caught it -- every track here is generated by walking a real path at
// a real speed (mkTrack).
//
// Extracts the real QGeo/QUEST_TUNING and the real method bodies straight out
// of the shipped file, so this tests the code that ships, not a
// reimplementation (same technique as tests/cylinder-segment-cross.test.js).
// The trailing api() POST in _classifyAndLog needs a live session/fetch and
// belongs to a manual on-mountain test.
//
// Run: `node --test tests/quest-corridor-detection.test.js` (or as part of the
// full `node --test tests/` suite).
"use strict";
const fs = require("fs");
const path = require("path");

let pass = 0, fail = 0;
function assert(cond, msg) { if (cond) pass++; else { fail++; console.log("FAIL:", msg); } }

const html = fs.readFileSync(path.join(__dirname, "../frontend/ridge-quest.html"), "utf8");

// ---- extract QGeo + QUEST_TUNING ----
const qgeoM = html.match(/const QGeo = \{[\s\S]*?\n\};/);
if (!qgeoM) { console.log("FAIL: could not extract QGeo from ridge-quest.html"); process.exit(1); }
const QGeo = eval("(" + qgeoM[0].replace(/^const QGeo = /, "").replace(/;$/, "") + ")");
const tuningM = html.match(/const QUEST_TUNING = \{[\s\S]*?\n\};/);
if (!tuningM) { console.log("FAIL: could not extract QUEST_TUNING from ridge-quest.html"); process.exit(1); }
const QUEST_TUNING = eval("(" + tuningM[0].replace(/^const QUEST_TUNING = /, "").replace(/;$/, "") + ")");

// ---- extract Quest._classifyAndLog's body, stopping before the api() POST ----
const startTag = "_classifyAndLog(corridor, buffer, selectedActivity, isFinal){";
const startIdx = html.indexOf(startTag);
if (startIdx < 0) { console.log("FAIL: could not find _classifyAndLog in ridge-quest.html"); process.exit(1); }
const endTag = "\n    api(\"/api/quest-runs\"";
const endIdx = html.indexOf(endTag, startIdx);
if (endIdx < 0) { console.log("FAIL: could not find end of _classifyAndLog body in ridge-quest.html"); process.exit(1); }
// eslint-disable-next-line no-new-func
const classifyRaw = new Function("corridor", "buffer", "selectedActivity", "isFinal", "QGeo", "QUEST_TUNING",
  html.slice(startIdx + startTag.length, endIdx) + "\nreturn run;");
// Old call shape (corridor, buffer, activity, QGeo, QUEST_TUNING), as a
// player who has LEFT the corridor (isFinal). Returns the run, or undefined.
function classify(corridor, buffer, sel, QG, QT) {
  const r = classifyRaw.call(this, corridor, buffer, sel, true, QG, QT);
  return (r && typeof r === "object") ? r : undefined;
}

// ---- extract Quest._tick's body by brace matching ----
function extractMethodBody(tag) {
  const s = html.indexOf(tag);
  if (s < 0) { console.log("FAIL: could not find " + tag); process.exit(1); }
  let depth = 0, i = html.indexOf("{", s); const bodyStart = i + 1;
  for (; i < html.length; i++) {
    if (html[i] === "{") depth++;
    else if (html[i] === "}") { depth--; if (depth === 0) break; }
  }
  return html.slice(bodyStart, i);
}
// eslint-disable-next-line no-new-func
const tickFn = new Function("corridor", "p", "selectedActivity", "QGeo", "QUEST_TUNING",
  extractMethodBody("_tick(corridor, p, selectedActivity){"));

// A Quest stand-in wired to the REAL _tick and REAL _classifyAndLog.
function makeQuest(corridors) {
  const logged = [], feedback = [];
  const Q = {
    states: {}, corridors, selectedActivity: "ski", onNarrate: null,
    onCoverage: (name, pct, passed, reason) => feedback.push({ name, pct, passed, reason }),
    _classifyAndLog(c, b, s, isFinal) {
      const r = classifyRaw.call(Q, c, b, s, isFinal, QGeo, QUEST_TUNING);
      if (r && typeof r === "object") { logged.push(r); return true; }
      return r;
    }
  };
  return { Q, logged, feedback };
}
function feed(Q, corridor, fixes, sel) {
  fixes.forEach(f => tickFn.call(Q, corridor, f, sel || "ski", QGeo, QUEST_TUNING));
}

// ---- fixtures ----
// Straight north-south corridors near Golden BC; path[0] is "top" (higher lat).
const straightRun = {
  zoneId: "z1", name: "Test Run", difficulty: "blue", runType: "run", widthM: 20,
  path: [[51.310, -117.05], [51.300, -117.05]], ref: [51.305, -117.05]           // ~1113 m
};
const liftLine = {
  zoneId: "z2", name: "Test Lift", difficulty: null, runType: "lift", widthM: 15,
  path: [[51.310, -117.05], [51.300, -117.05]], ref: [51.305, -117.05]
};
const hikeRoute = {
  zoneId: "z3", name: "Test Hike", difficulty: null, runType: "hike", widthM: 15,
  path: [[51.310, -117.05], [51.300, -117.05]], ref: [51.305, -117.05]
};
const shortRun = {                                                                // ~90 m
  zoneId: "z4", name: "Short Run", difficulty: "black", runType: "run", widthM: 8,
  path: [[51.30081, -117.05], [51.30000, -117.05]], ref: [51.300405, -117.05]
};
const chute = {                                                                   // ~300 m, 4 m wide
  zoneId: "z5", name: "Test Chute", difficulty: "double-black", runType: "chute", widthM: 4,
  path: [[51.3027, -117.05], [51.3000, -117.05]], ref: [51.30135, -117.05]
};
const withDescent = (c, m) => Object.assign({}, c, { descentM: m });

const BASE = 1700000000000;
// Positions along a corridor by arc length (m from path[0]).
function alongPath(c) {
  const cum = [0];
  for (let i = 1; i < c.path.length; i++) cum.push(cum[i - 1] + QGeo.haversineM(c.path[i - 1], c.path[i]));
  return { pts: c.path, cum, L: cum[cum.length - 1] };
}
function posAt(P, s) {
  s = Math.max(0, Math.min(P.L, s));
  let i = 1; while (i < P.cum.length - 1 && P.cum[i] < s) i++;
  const f = (s - P.cum[i - 1]) / (P.cum[i] - P.cum[i - 1]), a = P.pts[i - 1], b = P.pts[i];
  return [a[0] + (b[0] - a[0]) * f, a[1] + (b[1] - a[1]) * f];
}
// A realistic fix stream: walks fraction `from`->`to` of the corridor (0 = top)
// at `speed` m/s, one fix per `dt` s, optional lateral offset/noise (m, east).
function mkTrack(c, o) {
  o = Object.assign({ from: 0, to: 1, speed: 6, dt: 1, lateralM: 0, noiseM: 0, acc: 8, t0: 0, alt0: null, alt1: null }, o);
  const P = alongPath(c), s0 = o.from * P.L, s1 = o.to * P.L;
  const n = Math.max(1, Math.ceil(Math.abs(s1 - s0) / o.speed / o.dt));
  const out = [];
  for (let i = 0; i <= n; i++) {
    const f = i / n;
    let [lat, lon] = posAt(P, s0 + (s1 - s0) * f);
    lon += (o.lateralM + o.noiseM * Math.sin(i * 1.7 + 1)) / QGeo.mPerDegLon(lat);
    lat += (o.noiseM * 0.5 * Math.sin(i * 2.3)) / QGeo.mPerDegLat;
    out.push({ lat, lon, t: BASE + (o.t0 + i * o.dt) * 1000, speed: o.speed, acc: o.acc,
      alt: o.alt0 != null ? o.alt0 + (o.alt1 - o.alt0) * f : null });
  }
  return out;
}
// A straight east-west crossing of the corridor at fraction `at`, +-spanM.
function mkCross(c, at, o) {
  o = Object.assign({ spanM: 100, speed: 1.5, dt: 1, acc: 8, t0: 0 }, o);
  const P = alongPath(c), [lat0, lon0] = posAt(P, at * P.L);
  const n = Math.ceil(2 * o.spanM / o.speed / o.dt), out = [];
  for (let i = 0; i <= n; i++) {
    const off = -o.spanM + (2 * o.spanM) * (i / n);
    out.push({ lat: lat0, lon: lon0 + off / QGeo.mPerDegLon(lat0), t: BASE + (o.t0 + i * o.dt) * 1000, speed: o.speed, acc: o.acc, alt: null });
  }
  return out;
}
const last = a => a[a.length - 1];
const tEnd = a => (last(a).t - BASE) / 1000;

// ---- QGeo.corridorDist ----

(function testCorridorDistInsideBand() {
  const d = QGeo.corridorDist([51.305, -117.05], straightRun, straightRun.ref);
  assert(d < 0, "a point on the corridor centerline is inside the band (d<0), got " + d);
})();

(function testCorridorDistOutsideBand() {
  const d = QGeo.corridorDist([51.305, -117.048], straightRun, straightRun.ref);
  assert(d > 0, "a point far off the centerline is outside the band (d>0), got " + d);
})();

(function testCorridorDistHalfWidthBoundary() {
  const halfWidthDeg = (straightRun.widthM / 2) / QGeo.mPerDegLon(51.305);
  const d = QGeo.corridorDist([51.305, -117.05 + halfWidthDeg], straightRun, straightRun.ref);
  assert(Math.abs(d) < 0.5, "point exactly at the half-width offset has d~=0, got " + d);
})();

// ---- QGeo.projectOnPath ----

(function testProjectOnPathAlongTrack() {
  const G = QGeo.geom(straightRun);
  const mid = QGeo.projectOnPath([51.305, -117.05], G, null);
  assert(Math.abs(mid.s - G.L / 2) < 2 && mid.d < 0.5, "midpoint projects to ~half the length, d~0, got s=" + mid.s + " d=" + mid.d);
  const top = QGeo.projectOnPath([51.310, -117.05], G, null);
  assert(top.s < 1, "path[0] projects to s~0, got " + top.s);
  assert(Math.abs(G.L - 1113) < 5, "corridor length ~1113 m, got " + G.L);
})();

(function testProjectOnPathHintPicksNearbyLegOfAHairpin() {
  // A hairpin: down 200 m, across 6 m, back up 200 m -- the two legs are ~6 m
  // apart, so a point between them is near-equidistant from both. The hint
  // (where the previous fix was) must pick the leg the skier is on.
  const hairpin = { zoneId: "h", name: "Hairpin", runType: "run", widthM: 6,
    path: [[51.3020, -117.0500], [51.3002, -117.0500], [51.3002, -117.04991], [51.3020, -117.04991]],
    ref: [51.3011, -117.0500] };
  const G = QGeo.geom(hairpin);
  const p = [51.3010, -117.049955]; // between the legs, mid-way
  const nearFirst = QGeo.projectOnPath(p, G, 40);            // hint: early on the first leg
  const nearLast = QGeo.projectOnPath(p, G, G.L - 40);       // hint: late on the return leg
  assert(nearFirst.s < G.L / 2 && nearLast.s > G.L / 2, "hint disambiguates the hairpin's two legs, got " + nearFirst.s + " / " + nearLast.s);
})();

// ---- a genuine full pass, classified ----

(function testSkiDescendingFastEnough() {
  const run = classify(straightRun, mkTrack(straightRun, { speed: 8 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "ski", "a full descent at ski pace classifies as ski, got " + (run && run.activity));
  assert(run && run.avgSpeedMps > 6 && run.avgSpeedMps < 10, "avg speed reflects the real pace, got " + (run && run.avgSpeedMps));
})();

(function testHikeDescendingTooSlow() {
  const run = classify(straightRun, mkTrack(straightRun, { speed: 1.2, dt: 5 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "hike", "a full descent at walking pace classifies as hike (skinning/walking down), got " + (run && run.activity));
})();

(function testHikeAscendingOnPlainRun() {
  const run = classify(straightRun, mkTrack(straightRun, { from: 1, to: 0, speed: 1.2, dt: 5 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "hike", "walking UP a plain run is a hike, never ski, got " + (run && run.activity));
})();

(function testAscendingFastIsRejectedNotHike() {
  // Riding a gondola parallel to a run at 4.5 m/s "up" the run: too fast to be
  // on foot -> rejected, not credited as a hike.
  const fb = [];
  const run = classify.call({ onCoverage: (n, p, ok, why) => fb.push({ ok, why }) },
    straightRun, mkTrack(straightRun, { from: 1, to: 0, speed: 8, dt: 1 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "an 8 m/s ascent is not a hike, got " + JSON.stringify(run));
  assert(fb.length === 1 && fb[0].ok === false && /too fast/.test(fb[0].why), "the player is told why, got " + JSON.stringify(fb));
})();

(function testLiftAscending() {
  const run = classify(liftLine, mkTrack(liftLine, { from: 1, to: 0, speed: 4, dt: 5 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "lift", "riding UP a lift corridor classifies as lift, got " + (run && run.activity));
})();

(function testLiftDescendingDiscarded() {
  const run = classify(liftLine, mkTrack(liftLine, { speed: 4, dt: 5 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "going DOWN a lift corridor (foot traffic) is discarded, got " + JSON.stringify(run));
})();

(function testWalkingUpALiftLineIsNotALiftRide() {
  const run = classify(liftLine, mkTrack(liftLine, { from: 1, to: 0, speed: 1.3, dt: 5 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "walking up a lift line at 1.3 m/s is not a lift ride, got " + JSON.stringify(run));
})();

(function testHikeRouteEitherDirectionIsHike() {
  const down = classify(hikeRoute, mkTrack(hikeRoute, { speed: 1.2, dt: 5 }), "ski", QGeo, QUEST_TUNING);
  const up = classify(hikeRoute, mkTrack(hikeRoute, { from: 1, to: 0, speed: 1.2, dt: 5 }), "ski", QGeo, QUEST_TUNING);
  assert(down && down.activity === "hike" && up && up.activity === "hike", "a runType:hike corridor is a hike in either direction");
})();

(function testHikeRunTooFastToBeOnFoot() {
  const run = classify(hikeRoute, mkTrack(hikeRoute, { speed: 9, dt: 2 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "9 m/s along a hike trail is not hiking, got " + JSON.stringify(run));
})();

// ---- chute: skied when descended, hiked when climbed, never when stood on ----

(function testChuteDescendingIsSkiEvenCautiously() {
  const run = classify(chute, mkTrack(chute, { speed: 1.5, dt: 3 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "ski", "a slowly skied chute is still ski (2026-09-17 rule kept), got " + (run && run.activity));
})();

(function testChuteAscendingIsHikeNotSki() {
  const run = classify(chute, mkTrack(chute, { from: 1, to: 0, speed: 1.2, dt: 3 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "hike", "climbing a chute is a hike -- it used to score as ski either way, got " + (run && run.activity));
})();

(function testChuteStandingStillNotSkiing() {
  const run = classify(chute, mkTrack(chute, { speed: 0.3, dt: 10 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "0.3 m/s down a chute is not skiing it, got " + JSON.stringify(run));
})();

// ---- THE FIELD BUG: crossing / traversing must not log a run ----

(function testPerpendicularTraverseAcrossMidRunIsNotARun() {
  const fb = [];
  const run = classify.call({ onCoverage: (n, p, ok, why) => fb.push({ ok, why }) },
    straightRun, mkCross(straightRun, 0.5, { speed: 1.5 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "a slow east-west crossing of a run is not a run, got " + JSON.stringify(run));
  assert(fb.length === 0, "a plain traverse stays silent (no 'not counted' noise), got " + JSON.stringify(fb));
})();

(function testTraverseAcrossShortCorridorIsNotARun() {
  // The exact shape the old 50%-coverage/15m-tolerance test passed: a slow
  // crossing of a ~90 m corridor covers most of its length within tolerance.
  const run = classify(shortRun, mkCross(shortRun, 0.5, { spanM: 60, speed: 1.2 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "crossing a ~90 m corridor is not a run, got " + JSON.stringify(run));
})();

(function testDiagonalCutAcrossShortCorridorIsNotARun() {
  // ~30 m sideways over the corridor's ~70 m interior, at ski pace.
  const P = alongPath(shortRun), out = [];
  for (let i = 0; i <= 14; i++) {
    const s = 10 + (70 * i) / 14, off = 30 - (60 * i) / 14;
    const [lat, lon] = posAt(P, s);
    out.push({ lat, lon: lon + off / QGeo.mPerDegLon(lat), t: BASE + i * 1000, speed: 5, acc: 8, alt: null });
  }
  const run = classify(shortRun, out, "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "a diagonal cut across a short corridor is not a run, got " + JSON.stringify(run));
})();

(function testTraverseClippingOnlyTheTopIsNotARun() {
  const run = classify(straightRun, mkCross(straightRun, 0.03, { speed: 2 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "clipping the top of a run is not a run, got " + JSON.stringify(run));
})();

(function testTraverseBelowTheTopEnteringMidRunAndSkiingToTheBottomIsNotARun() {
  const fb = [];
  const run = classify.call({ onCoverage: (n, p, ok, why) => fb.push({ pct: p, ok, why }) },
    straightRun, mkTrack(straightRun, { from: 0.45, to: 1, speed: 8 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "dropping in mid-run and skiing the bottom half doesn't count, got " + JSON.stringify(run));
  assert(fb.length === 1 && /top/.test(fb[0].why) && fb[0].ok === false, "told it never reached the top, got " + JSON.stringify(fb));
  assert(fb[0].pct > 0.4 && fb[0].pct < 0.7, "reported coverage reflects the ~55% skied, got " + (fb[0] && fb[0].pct));
})();

(function testTopThenLeavingHalfwayIsNotARun() {
  const fb = [];
  const run = classify.call({ onCoverage: (n, p, ok, why) => fb.push({ ok, why }) },
    straightRun, mkTrack(straightRun, { from: 0, to: 0.6, speed: 8 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "skiing 60% then leaving doesn't count, got " + JSON.stringify(run));
  assert(fb.length === 1 && /bottom/.test(fb[0].why), "told it never reached the bottom, got " + JSON.stringify(fb));
})();

(function testSkiingParallelFarFromTheCorridorIsNotARun() {
  const run = classify(straightRun, mkTrack(straightRun, { speed: 8, lateralM: 80 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "skiing a full length 80 m off to the side is a different run, got " + JSON.stringify(run));
})();

(function testTopThenWanderingOffThenBottomIsNotARun() {
  const a = mkTrack(straightRun, { from: 0, to: 0.06, speed: 6 });
  const away = mkTrack(straightRun, { from: 0.06, to: 0.9, speed: 6, lateralM: 150, t0: tEnd(a) });
  const b = mkTrack(straightRun, { from: 0.94, to: 1, speed: 6, t0: tEnd(away) + 5 });
  const run = classify(straightRun, a.concat(away, b), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "touching both ends but skipping the middle isn't a run, got " + JSON.stringify(run));
})();

(function testImpossiblySpeedIsAGpsJump() {
  const buffer = [
    { lat: 51.310, lon: -117.05, t: BASE, speed: 6, acc: 8, alt: null },
    { lat: 51.300, lon: -117.05, t: BASE + 10000, speed: 6, acc: 8, alt: null }   // 1.1 km in 10 s
  ];
  const run = classify(straightRun, buffer, "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "1.1 km in 10 s (~111 m/s) is a GPS jump, not a run, got " + JSON.stringify(run));
})();

(function testPoorAccuracyFixesCountForNothing() {
  const run = classify(straightRun, mkTrack(straightRun, { speed: 8, acc: 80 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "fixes with 80 m accuracy can't verify a run, got " + JSON.stringify(run));
})();

// ---- a real run must survive GPS reality ----

(function testFullDescentWithGpsJitterStillPasses() {
  const run = classify(straightRun, mkTrack(straightRun, { speed: 8, noiseM: 6, acc: 10 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "ski", "a full descent with +-6 m GPS wobble still counts, got " + JSON.stringify(run && run.activity));
})();

(function testNarrowChuteWithJitterStillPasses() {
  // The old exit-on-first-fix-outside-a-3m-band would chop this into fragments.
  const run = classify(chute, mkTrack(chute, { speed: 4, noiseM: 5, acc: 8 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "ski", "a full descent of a 4 m chute with +-5 m wobble still counts, got " + JSON.stringify(run && run.activity));
})();

(function testFullDescentSparseBufferPasses() {
  // A fast mover's fixes are sparse (200 m apart here: 20 m/s, one fix per 10 s),
  // but the polyline they trace still covers the whole corridor, so a genuine
  // full descent isn't penalised for having few fixes.
  const run = classify(straightRun, mkTrack(straightRun, { speed: 20, dt: 10 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "ski", "a sparse (10 s apart) full-length pass still passes, got " + JSON.stringify(run && run.activity));
})();

(function testLongGpsBlackoutIsNotBridged() {
  // Two fixes 40 s apart (> BRIDGE_S): nothing verifies what happened between
  // them, so the middle of the corridor is uncovered.
  const buffer = [
    { lat: 51.310, lon: -117.05, t: BASE, speed: 6, acc: 8, alt: null },
    { lat: 51.300, lon: -117.05, t: BASE + 40000, speed: 6, acc: 8, alt: null }
  ];
  const run = classify(straightRun, buffer, "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "a 40 s blackout between the two ends can't be verified, got " + JSON.stringify(run && run.activity));
})();

(function testBriefGpsDropoutMidRunStillPasses() {
  const a = mkTrack(straightRun, { from: 0, to: 0.45, speed: 8 });
  const b = mkTrack(straightRun, { from: 0.55, to: 1, speed: 8, t0: tEnd(a) + 14 }); // ~14 s gap
  const run = classify(straightRun, a.concat(b), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "ski", "a 14 s GPS gap mid-run is bridged, got " + JSON.stringify(run && run.activity));
})();

(function testLapInOneBufferUsesTheFinalDescent() {
  // Hike up (bottom first), then ski down, in ONE buffer: the ski pass must be
  // found and timed from the LAST visit to the top, not from the hike's start.
  const up = mkTrack(straightRun, { from: 1, to: 0, speed: 1.2, dt: 5 });
  const down = mkTrack(straightRun, { from: 0, to: 1, speed: 8, t0: tEnd(up) + 60 });
  const run = classify(straightRun, up.concat(down), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "ski", "the descent after a hike-up is credited as ski, got " + JSON.stringify(run && run.activity));
  assert(run && run.durationS < 300, "run time is the descent only, not the hike-up too, got " + (run && run.durationS));
})();

// ---- elevation ----

(function testDescentWithMatchingAltitudeCounts() {
  const c = withDescent(straightRun, 300);
  const run = classify(c, mkTrack(c, { speed: 8, alt0: 2400, alt1: 2100 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "ski", "a descent whose altitude actually drops ~300 m counts, got " + JSON.stringify(run && run.activity));
})();

(function testFlatAltitudeOnAClaimedDescentIsRejected() {
  const fb = [];
  const c = withDescent(straightRun, 300);
  const run = classify.call({ onCoverage: (n, p, ok, why) => fb.push({ ok, why }) },
    c, mkTrack(c, { speed: 8, alt0: 2400, alt1: 2400 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "300 m of authored descent with a flat altitude track is not a descent, got " + JSON.stringify(run && run.activity));
  assert(fb.length === 1 && /elevation/.test(fb[0].why), "told the elevation didn't match, got " + JSON.stringify(fb));
})();

(function testClimbingWhileGoingDownIsRejected() {
  const c = withDescent(straightRun, 300);
  const run = classify(c, mkTrack(c, { speed: 8, alt0: 2100, alt1: 2400 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "a 'descent' that gains 300 m of altitude is rejected, got " + JSON.stringify(run && run.activity));
})();

(function testMissingAltitudeNeverFailsARun() {
  const c = withDescent(straightRun, 300);
  const run = classify(c, mkTrack(c, { speed: 8 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "ski", "no altitude readings -> elevation check skipped, run still counts, got " + JSON.stringify(run && run.activity));
})();

(function testSmallDescentIsNotElevationChecked() {
  const c = withDescent(straightRun, 60);
  const run = classify(c, mkTrack(c, { speed: 8, alt0: 2400, alt1: 2400 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "ski", "phone altitude is too noisy to judge a 60 m drop; geometry alone decides, got " + JSON.stringify(run && run.activity));
})();

// ---- vertical for scoring ----

(function testAuthoredDescentDrivesVertical() {
  let cov = null;
  const self = { onCoverage: (n, pct, ok) => { if (ok) cov = pct; } };
  const c = withDescent(straightRun, 300);
  const run = classify.call(self, c, mkTrack(c, { speed: 8, alt0: 9999, alt1: 8888 }), "ski", QGeo, QUEST_TUNING);
  // (alt 9999->8888 is a 1111 m drop: passes the elevation check, then is IGNORED for scoring)
  assert(run && run.verticalM === -Math.round(300 * cov), "verticalM = -round(descentM x coverage), got " + (run && run.verticalM) + " cov=" + cov);
})();

(function testVerticalDeltaFromAltitudeWhenNoAuthoredDescent() {
  const run = classify(straightRun, mkTrack(straightRun, { speed: 8, alt0: 2400, alt1: 2100 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.verticalM != null && run.verticalM < -200, "legacy fallback: verticalM from the altitude delta, got " + (run && run.verticalM));
})();

(function testVerticalNullWithoutAltitudeOrAuthoredDescent() {
  const run = classify(straightRun, mkTrack(straightRun, { speed: 8 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.verticalM === null, "no altitude and no authored descent -> null, got " + (run && run.verticalM));
})();

(function testAuthoredDescentNeverNullOnHike() {
  const c = withDescent(straightRun, 300);
  const run = classify(c, mkTrack(c, { speed: 1.2, dt: 5 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "hike" && run.verticalM < 0, "a hike on a corridor with authored descent is never null verticalM, got " + JSON.stringify(run && { a: run.activity, v: run.verticalM }));
})();

(function testLiftAndDistanceActivitiesHaveNullVertical() {
  const lift = classify(withDescent(liftLine, 250), mkTrack(liftLine, { from: 1, to: 0, speed: 4, dt: 5 }), "ski", QGeo, QUEST_TUNING);
  assert(lift && lift.activity === "lift" && lift.verticalM === null, "a lift ride carries null verticalM (0 pts)");
  const bike = classify(withDescent(straightRun, 250), mkTrack(straightRun, { speed: 5 }), "bike", QGeo, QUEST_TUNING);
  assert(bike && bike.activity === "bike" && bike.verticalM === null, "bike scores on distance, so verticalM is null");
})();

// ---- selectedActivity (R8/R12) ----

(function testBikeDescendingFastEnough() {
  const run = classify(straightRun, mkTrack(straightRun, { speed: 5 }), "bike", QGeo, QUEST_TUNING);
  assert(run && run.activity === "bike", "descending at riding pace with bike selected is bike, got " + (run && run.activity));
  assert(run && run.distanceM > 1000 && run.distanceM <= 1113 * 1.25, "bike distance ~ the corridor's length, capped, got " + (run && run.distanceM));
})();

(function testBikeDescendingTooSlowFallsBackToHike() {
  const run = classify(straightRun, mkTrack(straightRun, { speed: 1.2, dt: 5 }), "bike", QGeo, QUEST_TUNING);
  assert(run && run.activity === "hike", "pushing the bike (too slow) falls back to hike, got " + (run && run.activity));
})();

(function testHikeSelectedAtWalkingPace() {
  const run = classify(straightRun, mkTrack(straightRun, { speed: 1.4, dt: 5 }), "hike", QGeo, QUEST_TUNING);
  assert(run && run.activity === "hike", "hike selected, walking pace, is hike, got " + (run && run.activity));
})();

(function testDriveSelectedAtDrivingPace() {
  const down = classify(straightRun, mkTrack(straightRun, { speed: 15, dt: 2 }), "drive", QGeo, QUEST_TUNING);
  const up = classify(straightRun, mkTrack(straightRun, { from: 1, to: 0, speed: 15, dt: 2 }), "drive", QGeo, QUEST_TUNING);
  assert(down && down.activity === "drive" && up && up.activity === "drive", "drive is either direction at driving pace");
})();

(function testDriveSelectedWhileWalkingIsRejected() {
  const run = classify(straightRun, mkTrack(straightRun, { speed: 1.4, dt: 5 }), "drive", QGeo, QUEST_TUNING);
  assert(run === undefined, "walking with 'drive' selected doesn't score driving points, got " + JSON.stringify(run));
})();

(function testXcskiEitherDirection() {
  const down = classify(straightRun, mkTrack(straightRun, { speed: 2, dt: 4 }), "xcski", QGeo, QUEST_TUNING);
  const up = classify(straightRun, mkTrack(straightRun, { from: 1, to: 0, speed: 2, dt: 4 }), "xcski", QGeo, QUEST_TUNING);
  assert(down && down.activity === "xcski" && up && up.activity === "xcski", "xcski is either direction (Nordic trails are out-and-back)");
})();

(function testLiftOutranksSelection() {
  const run = classify(liftLine, mkTrack(liftLine, { from: 1, to: 0, speed: 4, dt: 5 }), "bike", QGeo, QUEST_TUNING);
  assert(run && run.activity === "lift", "riding up a lift corridor is a lift regardless of selection, got " + (run && run.activity));
})();

(function testHikeRouteOutranksSelection() {
  const run = classify(hikeRoute, mkTrack(hikeRoute, { from: 1, to: 0, speed: 1.5, dt: 5 }), "bike", QGeo, QUEST_TUNING);
  assert(run && run.activity === "hike", "a runType:hike corridor stays hike regardless of selection, got " + (run && run.activity));
})();

(function testGondolaOverARunIsNotAHike() {
  // A hike "up" the run at 4.5 m/s (under the on-foot speed cap) that lies
  // inside a lift corridor's band is a lift ride, not a hike.
  const self = { corridors: [liftLine, straightRun] };
  const run = classify.call(self, straightRun, mkTrack(straightRun, { from: 1, to: 0, speed: 4.5, dt: 2 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "riding a lift that runs along a run is not a hike, got " + JSON.stringify(run && run.activity));
})();

(function testGondolaOverARunIsNotASkiedRun() {
  // Field report 2026-09-23: riding the gondola up credited the runs
  // underneath as SKIED. Direction comes from the corridor's own geometry
  // (which end zone was reached first), so a run whose "top" end the gondola
  // reaches first reads as a DOWN pass and takes the ski branch at gondola
  // speed -- the old guard only covered an ASCENDING HIKE, so nothing caught
  // it. No altitude here (mkTrack's default), so the elevation check is
  // skipped and the lift-band overlap has to be what decides.
  const self = { corridors: [liftLine, straightRun] };
  const run = classify.call(self, straightRun, mkTrack(straightRun, { from: 0, to: 1, speed: 5, dt: 2 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "a 'down' pass at gondola speed inside a lift band is a lift ride, not a skied run, got " + JSON.stringify(run && run.activity));
})();

(function testGondolaRideWithRealisticGpsDriftIsStillALiftRide() {
  // Live Kicking Horse data (2026-09-24): the gondola is authored 10 m wide, but a phone on a
  // mountain sits 5-10 m off the cable, so with the bare band a real ride put too few fixes
  // "inside" and slipped past the guard. A rider drifting 8 m off a 10 m-wide lift line must
  // still be recognised as riding it (LIFT_BAND_EXTRA_M).
  const gondola = Object.assign({}, liftLine, { widthM: 10 });
  const self = { corridors: [gondola, straightRun] };
  const drift = classify.call(self, straightRun, mkTrack(straightRun, { from: 0, to: 1, speed: 5, dt: 2, lateralM: 8 }), "ski", QGeo, QUEST_TUNING);
  assert(drift === undefined, "a ride 8 m off a 10 m gondola line is still a lift ride, got " + JSON.stringify(drift && drift.activity));
  // ...but a skier on a run whose centreline is 25 m from the gondola is not mistaken for a lift
  // rider (the widened band reaches only halfwidth + LIFT_BAND_EXTRA_M = 10 m).
  const dLon = 25 / QGeo.mPerDegLon(51.305);
  const farGondola = Object.assign({}, gondola, { path: gondola.path.map(([la, lo]) => [la, lo + dLon]), ref: [gondola.ref[0], gondola.ref[1] + dLon] });
  const clear = classify.call({ corridors: [farGondola, straightRun] }, straightRun, mkTrack(straightRun, { from: 0, to: 1, speed: 5, dt: 2 }), "ski", QGeo, QUEST_TUNING);
  assert(clear && clear.activity === "ski", "a run 25 m from the gondola still scores, got " + JSON.stringify(clear && clear.activity));
})();

(function testRunUnderALiftStillScoresWhenAltitudeConfirmsIt() {
  // The flip side of the guard above: a run genuinely skied directly under a
  // gondola must STILL score when the device has usable altitude -- a
  // verified descent beats the 2D lift-band overlap test. Without this the
  // fix would just trade false credits for false rejections on exactly the
  // runs that lie under a lift line.
  const c = withDescent(straightRun, 300);
  const self = { corridors: [liftLine, c] };
  const run = classify.call(self, c, mkTrack(c, { from: 0, to: 1, speed: 5, dt: 2, alt0: 2300, alt1: 2000 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "ski", "a real descent under a lift line still scores when altitude confirms it, got " + JSON.stringify(run && run.activity));
})();

// ---- duration ----

(function testTooQuickDiscarded() {
  const run = classify(shortRun, mkTrack(shortRun, { speed: 40, dt: 0.5 }), "ski", QGeo, QUEST_TUNING);
  assert(run === undefined, "a 'run' shorter than MIN_DURATION_S is flicker, got " + JSON.stringify(run));
})();

(function testTooLongDiscarded() {
  const run = classify(straightRun, mkTrack(straightRun, { speed: 0.18, dt: 60 }), "hike", QGeo, QUEST_TUNING);
  assert(run === undefined, "a >90 min pass of a 1.1 km corridor is stuck GPS, not a run, got " + JSON.stringify(run));
})();

(function testLongCorridorRaisesTheDurationCap() {
  // ~10 km corridor: a 110-minute pass must NOT be discarded (R12, 2026-08-19).
  const longC = { zoneId: "zl", name: "Long", runType: "run", widthM: 20, lengthM: 10000,
    path: [[51.39, -117.05], [51.30, -117.05]], ref: [51.345, -117.05] };
  const run = classify(longC, mkTrack(longC, { speed: 1.5, dt: 10 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "hike", "a ~110 min pass of a 10 km corridor is kept once the cap scales with length, got " + JSON.stringify(run && run.activity));
})();

// ---- feedback ----

(function testOnCoverageFiresOnceWhenLogged() {
  const calls = [];
  classify.call({ onCoverage: (name, pct, passed) => calls.push({ name, pct, passed }) },
    straightRun, mkTrack(straightRun, { speed: 8 }), "ski", QGeo, QUEST_TUNING);
  assert(calls.length === 1 && calls[0].name === "Test Run" && calls[0].passed === true && calls[0].pct > 0.9,
    "a logged run reports one passed:true with high coverage, got " + JSON.stringify(calls));
})();

(function testProbeFailuresAreSilent() {
  // isFinal=false (mid-recording probe): a not-yet-complete pass says nothing.
  const calls = [];
  const r = classifyRaw.call({ onCoverage: (...a) => calls.push(a) }, straightRun,
    mkTrack(straightRun, { from: 0, to: 0.6, speed: 8 }), "ski", false, QGeo, QUEST_TUNING);
  assert(r === false && calls.length === 0, "a probe of an incomplete pass returns false and stays silent, got " + r + " / " + calls.length);
})();

// ---- Quest._tick: narration band (unchanged behaviour) ----

function makeNarrationThis() { return { states: {}, onNarrate: null, _classifyAndLog() { return false; } }; }

(function testTickNarratesOnNarrowCorridor() {
  const narrow = { zoneId: "nc1", name: "Test Chute", say: "test chute", runType: "chute", widthM: 4,
    path: [[51.310, -117.05], [51.300, -117.05]], ref: [51.305, -117.05] };
  const self = makeNarrationThis();
  let narrated = null;
  self.onNarrate = (text, zoneId) => { narrated = { text, zoneId }; };
  tickFn.call(self, narrow, { lat: 51.305, lon: -117.05, t: BASE, acc: 8 }, "ski", QGeo, QUEST_TUNING);
  assert(narrated !== null, "standing on a 4m-wide corridor's centerline fires narration (old fixed 3m margin made this impossible)");
  assert(narrated && narrated.text === "test chute", "narration receives the corridor's own say text");
})();

(function testTickHysteresisStillGuardsWideCorridor() {
  const wide = { zoneId: "wc1", name: "Wide Run", say: "wide run", runType: "run", widthM: 20,
    path: [[51.310, -117.05], [51.300, -117.05]], ref: [51.305, -117.05] };
  const halfW = 10;
  const barely = makeNarrationThis();
  let barelyNarrated = false;
  barely.onNarrate = () => { barelyNarrated = true; };
  const nearEdgeLon = -117.05 + (halfW - 1) / (111320 * Math.cos(51.305 * Math.PI / 180));
  tickFn.call(barely, wide, { lat: 51.305, lon: nearEdgeLon, t: BASE, acc: 8 }, "hike", QGeo, QUEST_TUNING);
  assert(!barelyNarrated, "barely inside the true edge (less than the margin) does not yet count as entering");
  const clearly = makeNarrationThis();
  let clearlyNarrated = false;
  clearly.onNarrate = () => { clearlyNarrated = true; };
  tickFn.call(clearly, wide, { lat: 51.305, lon: -117.05, t: BASE, acc: 8 }, "hike", QGeo, QUEST_TUNING);
  assert(clearlyNarrated, "clearly inside (past the margin) counts as entering and narrates");
})();

(function testTickExitHysteresisIgnoresJitter() {
  const narrow = { zoneId: "nc2", name: "Test Chute", say: "test chute", runType: "chute", widthM: 4,
    path: [[51.310, -117.05], [51.300, -117.05]], ref: [51.305, -117.05] };
  const self = makeNarrationThis();
  let narrateCount = 0;
  self.onNarrate = () => { narrateCount++; };
  tickFn.call(self, narrow, { lat: 51.305, lon: -117.05, t: BASE, acc: 8 }, "ski", QGeo, QUEST_TUNING);
  assert(narrateCount === 1, "entered once");
  const justOutsideLon = -117.05 + 2.5 / (111320 * Math.cos(51.305 * Math.PI / 180));
  tickFn.call(self, narrow, { lat: 51.305, lon: justOutsideLon, t: BASE + 1000, acc: 8 }, "ski", QGeo, QUEST_TUNING);
  tickFn.call(self, narrow, { lat: 51.305, lon: -117.05, t: BASE + 2000, acc: 8 }, "ski", QGeo, QUEST_TUNING);
  assert(narrateCount === 1, "a small excursion under the exit margin doesn't flip phase, so no spurious re-narration on return");
})();

// ---- narration fires once per APPROACH (field log 2026-09-21: ~17 re-entries of a
// 4 m chute's ~1 m entry band in 4 minutes each restarted the voice) ----
(function testNarrationOncePerApproachDespiteGpsWander() {
  const narrow = { zoneId: "nw1", name: "Test Chute", say: "test chute", runType: "chute", widthM: 4,
    path: [[51.310, -117.05], [51.300, -117.05]], ref: [51.305, -117.05] };
  const self = makeNarrationThis();
  let count = 0; self.onNarrate = () => { count++; };
  const realNow = Date.now; let clock = BASE; Date.now = () => clock;
  try {
    const lonAt = m => -117.05 + m / QGeo.mPerDegLon(51.305);
    const at = (m, s) => ({ lat: 51.305, lon: lonAt(m), t: BASE + s * 1000, acc: 8 });
    // wander in and out across the narrow entry band 6 times, each excursion 5+ m out, 6 s apart
    for (let i = 0; i < 6; i++) {
      tickFn.call(self, narrow, at(0, i * 12), "ski", QGeo, QUEST_TUNING); clock += 6000;   // clearly inside
      tickFn.call(self, narrow, at(6, i * 12 + 6), "ski", QGeo, QUEST_TUNING); clock += 6000; // stepped out (still nearby)
    }
    assert(count === 1, "six in/out wanders around one chute narrate once, not every re-entry, got " + count);
    // genuinely leave (60 m away = beyond the recorder's hold band), then come back
    tickFn.call(self, narrow, at(60, 200), "ski", QGeo, QUEST_TUNING); clock += 6000;
    tickFn.call(self, narrow, at(0, 210), "ski", QGeo, QUEST_TUNING);
    assert(count === 2, "after genuinely leaving the area, the next approach narrates again, got " + count);
  } finally { Date.now = realNow; }
})();

// ---- narration audio is prefetched on approach (field log: 1762 ms from entry to sound) ----
(function testNarrationAudioPrefetchedOnApproachOncePerCorridor() {
  const c = { zoneId: "pf1", name: "Test Chute", say: "test chute", runType: "chute", widthM: 4,
    path: [[51.310, -117.05], [51.300, -117.05]], ref: [51.305, -117.05] };
  const self = makeNarrationThis(); const seen = []; self.onPrefetch = t => seen.push(t);
  const lonAt = m => -117.05 + m / QGeo.mPerDegLon(51.305);
  const at = (m, s) => ({ lat: 51.305, lon: lonAt(m), t: BASE + s * 1000, acc: 8 });
  tickFn.call(self, c, at(500, 0), "ski", QGeo, QUEST_TUNING);
  assert(seen.length === 0, "not prefetched while 500 m away");
  tickFn.call(self, c, at(150, 10), "ski", QGeo, QUEST_TUNING);
  assert(seen.length === 1 && seen[0] === "test chute", "prefetched once the player is within ~200 m");
  tickFn.call(self, c, at(120, 20), "ski", QGeo, QUEST_TUNING); tickFn.call(self, c, at(0, 30), "ski", QGeo, QUEST_TUNING);
  assert(seen.length === 1, "and only once per corridor per session, got " + seen.length);
  const noSay = Object.assign({}, c, { zoneId: "pf2", say: null }); const s2 = makeNarrationThis(); let n2 = 0; s2.onPrefetch = () => n2++;
  tickFn.call(s2, noSay, at(0, 0), "ski", QGeo, QUEST_TUNING);
  assert(n2 === 0, "a corridor with no narration never prefetches");
})();

// ---- Quest._tick: the run recorder, end to end (real _tick + real _classifyAndLog) ----

(function testTickLogsAFullDescentExactlyOnce() {
  const { Q, logged, feedback } = makeQuest([straightRun]);
  feed(Q, straightRun, mkTrack(straightRun, { speed: 8 }));
  assert(logged.length === 1 && logged[0].activity === "ski", "a full descent fed fix by fix logs exactly one ski run, got " + JSON.stringify(logged.map(r => r.activity)));
  assert(feedback.filter(f => f.passed).length === 1, "and reports it once");
})();

(function testTickLogsWithoutLeavingTheCorridor() {
  // The old detector only logged when the player left the band, so ending a
  // run in the lift-base queue (still inside) delayed it indefinitely.
  const { Q, logged } = makeQuest([straightRun]);
  feed(Q, straightRun, mkTrack(straightRun, { speed: 8, to: 0.97 }));
  assert(logged.length === 1, "a run is logged on reaching the far end zone, before/without leaving it, got " + logged.length);
})();

(function testTickTraverseLogsNothingAndSaysNothing() {
  const { Q, logged, feedback } = makeQuest([straightRun]);
  feed(Q, straightRun, mkCross(straightRun, 0.5, { speed: 1.5 }));
  feed(Q, straightRun, mkCross(straightRun, 0.5, { speed: 5, t0: 300 }));
  // then walk far away so the recorder closes and runs its final check
  feed(Q, straightRun, [{ lat: 51.305, lon: -117.04, t: BASE + 900000, acc: 8, speed: 1 }]);
  assert(logged.length === 0, "traversing across a corridor twice logs nothing, got " + logged.length);
  assert(feedback.length === 0, "and stays silent, got " + JSON.stringify(feedback));
})();

(function testTickTraverseAcrossManyAdjacentCorridors() {
  // The reported scenario: one traverse line crossing several nearby chutes.
  const cs = [0.2, 0.35, 0.5, 0.65, 0.8].map((at, i) => Object.assign({}, chute, {
    zoneId: "adj" + i, path: [[51.3027, -117.05 + i * 0.0006], [51.3000, -117.05 + i * 0.0006]], ref: [51.30135, -117.05 + i * 0.0006] }));
  const { Q, logged } = makeQuest(cs);
  const P = alongPath(chute), [lat0] = posAt(P, 0.5 * P.L), out = [];
  for (let i = 0; i <= 300; i++) {
    out.push({ lat: lat0, lon: -117.0510 + i * (0.0040 / 300), t: BASE + i * 1000, speed: 1.5, acc: 8, alt: null });
  }
  out.forEach(f => cs.forEach(c => tickFn.call(Q, c, f, "ski", QGeo, QUEST_TUNING)));
  assert(logged.length === 0, "a traverse crossing 5 adjacent chutes logs none of them, got " + logged.length);
})();

(function testTickDropInMidRunThenLeavingReportsWhyOnce() {
  const { Q, logged, feedback } = makeQuest([straightRun]);
  const t = mkTrack(straightRun, { from: 0.45, to: 1, speed: 8 });
  feed(Q, straightRun, t);
  // a full-length run needs both ends; this one only reached the bottom. Leave the area.
  feed(Q, straightRun, [{ lat: 51.30, lon: -117.03, t: last(t).t + 600000, acc: 8, speed: 5 }]);
  assert(logged.length === 0, "mid-run drop-in logs nothing, got " + logged.length);
  assert(feedback.length === 1 && feedback[0].passed === false && /top/.test(feedback[0].reason), "the player is told why exactly once, got " + JSON.stringify(feedback));
})();

(function testTickNarrowChuteWithJitterLogsOnce() {
  const { Q, logged } = makeQuest([chute]);
  feed(Q, chute, mkTrack(chute, { speed: 4, noiseM: 5, acc: 8 }));
  assert(logged.length === 1 && logged[0].activity === "ski", "a jittery descent of a 4 m chute logs one ski run (not fragments), got " + JSON.stringify(logged.map(r => r.activity)));
})();

(function testTickHikeUpThenSkiDownLogsBoth() {
  const realNow = Date.now; let clock = BASE;
  Date.now = () => clock;
  try {
    const { Q, logged } = makeQuest([straightRun]);
    const up = mkTrack(straightRun, { from: 1, to: 0, speed: 1.2, dt: 5 });
    feed(Q, straightRun, up);
    clock += 60000;                                  // past the post-log cooldown
    feed(Q, straightRun, mkTrack(straightRun, { speed: 8, t0: tEnd(up) + 60 }));
    assert(logged.length === 2 && logged[0].activity === "hike" && logged[1].activity === "ski",
      "walking up then skiing down logs a hike then a ski, got " + JSON.stringify(logged.map(r => r.activity)));
  } finally { Date.now = realNow; }
})();

// ---- REAL-DATA REGRESSION (prod quest_run + corridor rows, 2026-09-21) ----
// The field false-positives were Kicking Horse's short, WIDE chutes. Dimensions
// below are the real library values (width x length, authored loss). Logged
// on 09-18 within one minute: After Pride 8 s/49 m, Alley 17 14 s/60 m, South
// End Dump Run 17 s/65 m, each credited its full authored descent.
function blob(name, widthM, lengthM, lossM, lonOffsetM) {
  const lon = -117.05 + (lonOffsetM || 0) / QGeo.mPerDegLon(51.3005);
  const top = 51.3000 + lengthM / QGeo.mPerDegLat;
  return { zoneId: "rd-" + name, name, difficulty: "double-black", runType: "chute", activityType: "ski_chute",
    widthM, descentM: lossM, lengthM, path: [[top, lon], [51.3000, lon]], ref: [(top + 51.3000) / 2, lon] };
}
const afterPride = blob("After Pride", 75, 111, 81, 0);
const alley17 = blob("Alley 17", 50, 171, 106, 90);
const southEnd = blob("South End Dump Run", 50, 161, 113, 190);
const endZone = blob("End Zone", 100, 68, 0, 300);

(function testRealChuteDimensionsAreWideAndShort() {
  const G = QGeo.geom(afterPride);
  assert(Math.abs(G.L - 111) < 2 && afterPride.widthM === 75, "After Pride fixture is the real 75 m x 111 m blob, got L=" + G.L);
})();

(function testTraverseAcrossEachRealChuteIsNotARun() {
  [afterPride, alley17, southEnd, endZone].forEach(c => {
    const P = alongPath(c), [lat0, lon0] = posAt(P, 0.5 * P.L), out = [];
    const span = c.widthM / 2 + 12, n = Math.ceil(2 * span / 3.7);
    for (let i = 0; i <= n; i++) out.push({ lat: lat0, lon: lon0 + (-span + 2 * span * i / n) / QGeo.mPerDegLat * 1.6, t: BASE + i * 1000, speed: 3.7, acc: 8, alt: null });
    assert(classify(c, out, "ski", QGeo, QUEST_TUNING) === undefined, "a ~4 m/s traverse across " + c.name + " (" + c.widthM + " m wide) must not log, as it did in the field");
  });
})();

(function testFieldLogShapedCornerCutsAreRejected() {
  // The logged runs were 49-65 m of travel through a 111-171 m corridor: less
  // than the ~55-90 m along the corridor that reaching both end zones needs.
  [[afterPride, 49, 4.7], [alley17, 60, 3.7], [southEnd, 65, 3.8]].forEach(([c, dist, v]) => {
    const t = mkTrack(c, { from: 0.25, to: 0.25 + dist / QGeo.geom(c).L, speed: v, noiseM: 4 });
    assert(classify(c, t, "ski", QGeo, QUEST_TUNING) === undefined, c.name + ": " + dist + " m of travel in the middle of the corridor isn't a run");
  });
})();

(function testThreeAdjacentRealChutesTraversedInOneGoLogNothing() {
  const cs = [afterPride, alley17, southEnd];
  const { Q, logged } = makeQuest(cs);
  const P = alongPath(alley17), [lat0] = posAt(P, 0.5 * P.L), out = [];
  for (let i = 0; i <= 90; i++) out.push({ lat: lat0, lon: -117.05 - 60 / QGeo.mPerDegLon(lat0) + i * (330 / 90) / QGeo.mPerDegLon(lat0), t: BASE + i * 1000, speed: 3.7, acc: 8, alt: null });
  out.forEach(fx => cs.forEach(c => tickFn.call(Q, c, fx, "ski", QGeo, QUEST_TUNING)));
  out.push({ lat: 51.31, lon: -117.03, t: BASE + 900000, speed: 3, acc: 8, alt: null });
  cs.forEach(c => tickFn.call(Q, c, out[out.length - 1], "ski", QGeo, QUEST_TUNING));
  assert(logged.length === 0, "the reported scenario -- one traverse across 3 chutes -- logs none of them, got " + JSON.stringify(logged.map(r => r.runName)));
})();

(function testRealDescentOfAfterPrideStillCounts() {
  const run = classify(afterPride, mkTrack(afterPride, { speed: 6, noiseM: 10, acc: 10 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "ski" && run.verticalM < -60, "skiing After Pride top to bottom (10 m wobble) counts and scores its authored descent, got " + JSON.stringify(run && { a: run.activity, v: run.verticalM }));
})();

(function testFastRealDescentOfShortChuteStillCounts() {
  // ~11 m/s down 111 m: only a few seconds between the two end zones. The old
  // 8 s minimum would have thrown this genuine run away.
  const run = classify(afterPride, mkTrack(afterPride, { speed: 11, dt: 0.5 }), "ski", QGeo, QUEST_TUNING);
  assert(run && run.activity === "ski", "a fast (11 m/s) descent of a 111 m chute counts, got " + JSON.stringify(run && run.activity));
})();

(function testDiagonalTraverseAtConstantAltitudeIsRejectedByElevation() {
  // A diagonal cut through the whole blob at constant height (a real traverse):
  // geometry alone can't tell it from a descent -- the elevation check does.
  const P = alongPath(afterPride), out = [];
  for (let i = 0; i <= 30; i++) {
    const s = 8 + (95 * i) / 30, off = 28 - (56 * i) / 30, [lat, lon] = posAt(P, s);
    out.push({ lat, lon: lon + off / QGeo.mPerDegLon(lat), t: BASE + i * 3000, speed: 1.1, acc: 8, alt: 2000 + Math.sin(i) * 2 });
  }
  const fb = [];
  const run = classify.call({ onCoverage: (n, p, ok, why) => fb.push({ ok, why }) }, afterPride, out, "hike", QGeo, QUEST_TUNING);
  const asHike = run && run.activity;
  assert(run === undefined, "a constant-altitude diagonal through After Pride is a traverse, not a descent, got " + JSON.stringify(asHike));
  assert(fb.length === 1 && /elevation/.test(fb[0].why), "and the player is told the elevation didn't match, got " + JSON.stringify(fb));
  // the SAME line while actually dropping ~70 m is a real (diagonal) descent
  const dropping = out.map((fx, i) => Object.assign({}, fx, { alt: 2070 - 70 * (i / 30) }));
  const real = classify(afterPride, dropping, "hike", QGeo, QUEST_TUNING);
  // (a descended chute is ski by the 2026-09-17 rule, whatever the pace)
  assert(real && real.activity === "ski", "the same line with a real ~70 m drop counts, got " + JSON.stringify(real && real.activity));
})();

console.log(pass + " passed, " + fail + " failed");
if (fail > 0) process.exit(1);
